### ISSUE TITLE
Clicking X button for edited Sample in Container view doesn't cancel edit

### ISSUE THREAD

**Issue by jlmuir** [DiamondLightSource/SynchWeb#132]
**Steps to Reproduce**

1. Select a Proposal.
2. In the [current-proposal] menu, click Containers.
3. Click a Container in the list.
4. Click the Pencil button to edit an empty Location.
5. Select a Protein Acronym from the drop-down menu.  This changes the background of the Name textfield to red.
6. Click the X button of the Location being edited to cancel the edit.

**Expected Behavior**

The edit of the Location should be canceled, and the Check and X buttons should be replaced with the Pencil button.

**Actual Behavior**

Nothing happens.  The Location remains in edit mode.  The only way to recover is to reload the page or enter a valid Name and press the Check button to save it.

**Comment by ndg63276** [comment]
No longer an issue in the vue-style container pages.
