### ISSUE TITLE
Add Container button in Shipment view is too big

### ISSUE THREAD

**Issue by jlmuir** [DiamondLightSource/SynchWeb#134]
The Add Container button in the Shipment view is too big.  It appears to be taking on the height of the "Dewar Details" label on the left.  The button should be a normal size just like the "Add Dewar" button above it.

<img width="1046" alt="big-add-container" src="https://user-images.githubusercontent.com/959381/90820608-3e67a200-e2f7-11ea-8bd9-498233cecd92.png">

**Comment by stufisher** [comment]
This is by design, and after feedback from users. The first thing they want to do after creating a shipment is to create a new container (dewars have already been created). Therefore this is large to draw their attention to the button.
