### ISSUE TITLE
Clicking non-mx Proposal results in no Proposal being selected

### ISSUE THREAD

**Issue by jlmuir** [DiamondLightSource/SynchWeb#141]
**Steps to Reproduce**

1. Create a staff user who has only a `cm` Proposal.
2. For a regular user with no Proposals, create two: one with code `sw` and the other with code `mx`.
3. Log in as the staff user.
4. Click the Home button at the top.
5. Click Proposals.
6. Click the `sw` Proposal you just created for the regular user.

**Expected Behavior**

The Visit List view displays "No visits found", but the Proposal is selected, and you can click the Proposal's "sw[number]" drop-down menu to get the View All Data, Visits, Calendar, etc., menu items.

**Actual Behavior**

The Visit List view displays "No visits found", but the Proposal is *not* selected, and the selected Proposal drop-down menu that would have been labeled "sw[number]" instead is labeled "No Proposal" and does not display a drop-down menu when clicked.

**Notes**

Clicking the regular user's `mx` Proposal works fine; the problem only occurs when the user's non-`mx` Proposal is clicked.

**Comment by stufisher** [comment]
Every proposal must have at least one visit. WIthout a visit synchweb cant infer what type to show. At dls there is a dummy visit 0 to enable this

**Comment by jlmuir** [comment]
What do you mean by "dummy visit 0 to enable this"?  Do you mean that for every Proposal, you create a dummy Visit with `BLSession.visit_number` set to 0?  What do you set `startDate` and `endDate` to in this case?  Do you set `scheduled` to 0 so that it's not displayed on the calendar?  Do you set `archived` to 1?

**Comment by jlmuir** [comment]
I tried adding a Visit to the `sw` Proposal of the regular user, and that does _not_ make it work.

**Comment by stufisher** [comment]
You added a visit but _without_ a beamlinename so synchweb doesnt know what type the visit is => Access denied
