### ISSUE TITLE
Non-mx proposals not listed for user

### ISSUE THREAD

**Issue by jlmuir** [DiamondLightSource/SynchWeb#142]
**Steps to Reproduce**

1. For a regular user with no Proposals, create three: one with code `sw`, one with `mx`, and one with `in`.
2. Create a Visit on the `sw` and `mx` Proposals, but not the `in` Proposal.
3. Log in as the regular user.
4. Click the Home button at the top.
5. Click Proposals.

**Expected Behavior**

The Proposals list should include the `sw` and `mx` Proposals.  (I wish it included the `in` Proposal as well, but I understand that it's expected that it is not displayed because it has no Visits.)

**Actual Behavior**

The Proposals list only shows the `mx` Proposal.  The `sw` Proposal is not listed.

**Comment by stufisher** [comment]
You have not added Luke as a user on the visit, so it is not visible to the user...
