### ISSUE TITLE
Magnifying glass icon should mean search, not view

### ISSUE THREAD

**Issue by jlmuir** [DiamondLightSource/SynchWeb#200]
In the Dewar Details section of the Shipment view, each container in a dewar is listed with three icons: a printer, a magnifying glass, and an arrow cross.  The magnifying glass has a tool tip that says, "Click to View Container".  This is confusing UI design.  A magnifying glass always means _search_, not _view_.  The magnifying glass icon should be changed in this view, and in any other place where it is used to mean view, to something else.  In this case, perhaps it should be changed to an icon that looks like a container.  Or maybe the icon should just be removed, and instead the user should click on the list item or the name of the container to view it.

<img width="503" alt="shipment-dewar-details" src="https://user-images.githubusercontent.com/959381/109188308-6d544a00-7758-11eb-9ea4-caf05e145eb3.png">

**Comment by stufisher** [comment]
This is used throughout the ui, im afraid it isnt going to change
