### ISSUE TITLE
Can assign >1 container to same location in scanned Assign Containers view

### ISSUE THREAD

**Issue by jlmuir** [DiamondLightSource/SynchWeb#206]
It's possible to assign more than one container to the same sample changer location in the scanned Assign Containers view (e.g., `assign/scan/IMCA-CAT`), but that should not be allowed.  Server-side validation should be added to prevent this.  Here's one way to reproduce the problem:

1. Open two web browser windows.
2. Log in to SynchWeb in both windows, and open the scanned Assign Containers view in both.
3. In the first window, assign a container to an empty sample changer location.
4. In the second window, assign a different container to the same sample changer location.
5. (Now there are two containers assigned to the same sample changer location in the DB.)

I didn't test other assign-containers views, but it seems likely that they could have a similar problem.

**Comment by stufisher** [comment]
Its not easy to enforce this because there are historically a lot of containers left assigned. The imca branch now has a warning on your dedicated scan assignment page
