### ISSUE TITLE
Enabling PHP DB debugging breaks Shipment view

### ISSUE THREAD

**Issue by jlmuir** [DiamondLightSource/SynchWeb#210]
If I enable DB debugging in the [`_get_all_containers` function in `api/Page/Shipment.php`](https://github.com/DiamondLightSource/SynchWeb/blob/1709bfecf9c3449d051e39e4a4a93349b722f47f/api/src/Page/Shipment.php#L1259) by uncommenting the line

```
//$this->db->set_debug(True);
```

the Shipment view breaks: selecting a dewar in the Shipment Contents section results in no containers being displayed in the Dewar Details view even though the selected dewar has containers.

**Comment by stufisher** [comment]
Well yes, thats by design, enabling debugging does not return a json response, it returns the query and its results. You can inspect the request in the dev tools...
