### ISSUE TITLE
Editing Registered Container field in Container view is pain when list is large

### ISSUE THREAD

**Issue by jlmuir** [DiamondLightSource/SynchWeb#220]
In the Container view, when editing the Registered Container field, the drop-down menu is very long for some users with many registered containers, and it is not sorted alphanumerically.  One user has 171 registered containers, and it's difficult to find the right container in the drop-down because there are so many containers and they are not in alphanumeric order.  It would be nice if the drop-down were instead a combo box so that the user could type in part, or all, of the barcode to search for the registered container they want to select.  Also, the list should be sorted alphanumerically in either case (i.e., drop-down or combo box).

<img width="1148" alt="container-view-reg-container-edit" src="https://user-images.githubusercontent.com/959381/115441562-9c29f200-a1d6-11eb-96d4-e7f21c1aa7d4.png">

**Comment by stufisher** [comment]
Looks to me like the list is already sorted?

**Comment by jlmuir** [comment]
Hmm, I should have noted my exact use case, but I did not, so I can't go back to what caused me to submit this in the first place to verify.  However, my coworker had suggested a while back that it seemed to sort based on when the registered container was added, so I tried that, and indeed that seems to be the case.  For example, I just added a registered container with barcode `AAAA-01`, and added it to a proposal with a bunch of existing `LUKE-*` registered containers, and when I go to change the registered container, `AAAA-01` shows up at the bottom of the list, but it obviously should be at the top:

<img width="93" alt="reg-container-drop-down-sort" src="https://user-images.githubusercontent.com/959381/148575192-18780d53-2670-470e-b30f-908fc7227022.png">

**Comment by ndg63276** [comment]
The dropdown is now sorted alphanumerically on the vue-style container pages.
