### ISSUE TITLE
Give Name text field default focus in Add New Shipment view

### ISSUE THREAD

**Issue by jlmuir** [DiamondLightSource/SynchWeb#232]
When I click the "Add Shipment" button in the Shipments view, I'm taken to the "Add New Shipment" view, and the first field I always want to enter is the Name field, but I can't just start typing; I have to first click in the Name text field to give it focus, and then I can start typing.  I think every user will enter the shipment name first, so it seems like it would be good to give focus to this text field immediately on page load.

<img width="469" alt="add-new-shipment" src="https://user-images.githubusercontent.com/959381/121284349-53bbb600-c8a2-11eb-95f1-18958ac1b332.png">

**Comment by ndg63276** [comment]
Added as an internal issue at https://jira.diamond.ac.uk/browse/LIMS-693
