### ISSUE TITLE
Auto-processing ticks and crosses absent in some views, not others

### ISSUE THREAD

**Issue by benjaminhwilliams** [DiamondLightSource/SynchWeb#236]
In certain views, the ticks, crosses and spinning cogs that signify success/failure/progress of auto-processing jobs are missing and replaced with placeholder text.  In other views, the icons are present as expected.

On beamline I19 at DLS, we have recently changed the auto-processing recipes that we run.  In certain circumstances, there are now more auto-processing jobs than there were before.  This bug seems coincident with our changes, though I can see no reason why our changes should have caused this change in behaviour.

As an example, here's [the landing page for a recent visit](https://ispyb.diamond.ac.uk/dc/visit/cm28127-3), showing the missing ticks/crosses at the bottom-right:
![image](https://user-images.githubusercontent.com/11389015/127891394-c4cf4fb3-71b4-4921-99db-31dd12b29471.png)

Here's [a data collection group view](https://ispyb.diamond.ac.uk/dc/visit/cm28127-3/dcg/6070012) from that visit, showing the same problem:
![image](https://user-images.githubusercontent.com/11389015/127891513-acad1e7a-9ce5-4673-b2b5-0f3c9ae1d148.png)

On the other hand, here's the sample changer screen, with the first sample selected (I can't find a way of generating a permalink for this), showing the ticks and crosses as expected:
![image](https://user-images.githubusercontent.com/11389015/127891871-8d6a57a2-64ff-4164-bb72-69ee39730b29.png)

And here's [the auto-processing status summary](https://ispyb.diamond.ac.uk/dc/apstatussummary/visit/cm28127-3), which is also showing ticks and crosses:
![image](https://user-images.githubusercontent.com/11389015/127892043-8dd96728-66ae-4afb-89bf-ac4b3a4c61c6.png)

**Comment by ndg63276** [comment]
Seems to no longer be a problem.
