### ISSUE TITLE
Add New Container view allows creating samples without protein

### ISSUE THREAD

**Issue by jlmuir** [DiamondLightSource/SynchWeb#249]
I've been told that a sample must always have a protein assigned, but the "Add New Container" view (i.e., `/containers/add/did/<id>`) allows creating samples without a protein.

Steps to reproduce:

1. Click the "Add Container" button from the Shipment view.
2. Select a container from the Registered Container drop-down menu.
3. Enter `x1` in the Name column of sample location 1.
4. Click the "Clone from First Sample" button.
5. Click the "Add Container" button.

Actual Result:

It creates the container with the samples with no proteins assigned.

Expected Result:

It should produce a validation error that no protein is selected from the Protein Acronym drop-down for the samples.

**Comment by jlmuir** [comment]
Inspecting the DB, it seems SynchWeb creates the container but does not actually create the samples.  The samples are silently lost; no error message.

**Comment by ndg63276** [comment]
Seems to be no longer possible on the vue-style container pages.
