### ISSUE TITLE
Better use of browser real-estate?

### ISSUE THREAD

**Issue by CV-GPhL** [DiamondLightSource/SynchWeb#252]
Would it be possible to enlarge the used area for

- the main overview page: it seems to be hard-wired to use only 83.333% of the width with empty grey areas to the left and right
- the "View" pop-up window (which is both limited and fixed in width/height): it could easily use more width

I would find it even better, if the View pop-up windows would allow re-sizing when encountering HTML files (while starting from the currently computed size as a sensible initial default). I find the strict and enforced fixedwidth property rather limiting and odd in the context of looking at a HTML file.

**Comment by ndg63276** [comment]
By "the main overview page" I assume you mean eg https://ispyb.diamond.ac.uk/dc/visit/mx12345-123 ?

The "View" pop up (which I assume means within the "Logs and Files" page of an autoprocessing job) does now appear to be resizable, though I appreciate that may have happened in the 2 years since you opened this issue.

**Comment by CV-GPhL** [comment]
It is now resizeable indeed - good. However, the internal links (e.g. left "menu" in an autoPROC summery.html file) don't seem to work ... at least they don't for me.

**Comment by CV-GPhL** [comment]
"weird popup div" is the right description: seems to be designed mainly for display of small HTML snippets and not for a fully fledged HTML document? Maybe in such cases (like the summary.html from autoPROC) providing the same action for both the "View" and "Download" button could be more useful (with "View" opening in different "target" window/tab): we'd like to avoid users hitting "View" and then being stuck with a very partial view of a much longer and richer document. If the menu on the left doesn't work and (at least for me) there is no visible scrollbar on the right, users quickly get the impression of "nothing to see here", which would be unfortunate.

**Comment by ndg63276** [comment]
Merged in https://github.com/DiamondLightSource/SynchWeb/pull/706
