### ISSUE TITLE
"Unknown column" DB error on sample page

### ISSUE THREAD

**Issue by ejd53** [DiamondLightSource/SynchWeb#316]
Navigate to sample page, e.g., https://ispyb.diamond.ac.uk/samples/sid/3909536
Scroll to "Data Collections"
Click "Processing Errors"
See error at top of page:

**A database error has occurred
Unknown column 'app.datacollectionid' in 'on clause'359**

Request URI: https://ispyb.diamond.ac.uk/api/dc?page=1&per_page=15&total_pages=0&total_entries=0&sid=3909536&pp=5&t=err&prop=mx26794
Responds with 503 Service Unavailable, body {"title":"There was an error with MySQL","msg":"Unknown column 'app.datacollectionid' in 'on clause'359"}

**Comment by ndg63276** [comment]
I think this was fixed when https://github.com/DiamondLightSource/SynchWeb/pull/251 was merged in last October.
