### ISSUE TITLE
Would it be possible to remove `client/src/js/config.json` ?

### ISSUE THREAD

**Issue by dsclassen** [DiamondLightSource/SynchWeb#379]
I use Ansible to deploy SynchWeb to our server and I make changes to `client/src/js/config.json` during the process. Since this file is tracked in git, this causes all subsequent Ansible tasks to fail.

The `client/src/js/config_sample.json` file is still there for people to have a reference to start from, but maybe we could remove the DLS-specific `client/src/js/config.json` version? 

This would follow the pattern in `api` directory where there is no `api/config.php`. One is expected to make a copy of `api/config_sample.php` and customize it to your site.

I can always use "force" during the git checkout step so this isn't a huge deal.

**Comment by John-Holt-Tessella** [comment]
I don't see why not, but I am not sure I am significantly empowered to do this. I will talk with the team and then we will get it prioritised. Presumably this is not a new thing, but is there a timescale you need this fixing on?

**Comment by dsclassen** [comment]
I doubt this is of very high priority, and I guess I could just make a small PR myself to deal with it.

**Comment by John-Holt-Tessella** [comment]
That would be cool, we can then approve it.

**Comment by ndg63276** [comment]
Added as an internal issue at https://jira.diamond.ac.uk/browse/LIMS-694
