### ISSUE TITLE
Container > Extra Fields button shows '+' icon even when toggling off

### ISSUE THREAD

**Issue by jlmuir** [DiamondLightSource/SynchWeb#61]
In the Shipments > [Shipment Name] > Containers > Add Container view, there is an Extra Fields button that shows extra fields for the samples in the container:

<img width="469" alt="extra-fields" src="https://user-images.githubusercontent.com/959381/68251690-4add7100-ffe9-11e9-9fab-dee3826c5116.png">

But after pressing it to show the extra fields, you can press it again to hide the extra fields, but the icon is still the plus sign ('+') when you press it to hide the extra fields which is weird.

The plus icon ('+') should change to a minus icon ('-') when the extra fields are displayed.

Or the button could be changed to a "Show extra fields" checkbox, or perhaps a "Show extra fields" switch (if the UI toolkit supports it).

**Comment by stufisher** [comment]
Resolved in https://github.com/DiamondLightSource/SynchWeb/commit/dd2a58388a825f1e8db5129a56615eabb72197a2
