### ISSUE TITLE
User Office doesn't know whether Dewar booked in iSpyB for session 

### ISSUE THREAD

**Issue by LornaCG** [DiamondLightSource/SynchWeb#78]
The UO expenses procedure states that:

Diamond will cover the cost of shipping up to two dewars of your samples (per 8 hour shift) to beamlines and eBIC microscopes if your establishment is in the UK or EU. Details of the shipping arrangements can be found here.
 
      Where you ask Diamond to cover the costs of shipping samples and this is authorised by us, one      person fewer (than outlined in section 2 above) will be financially supported by us.
 
Currently UO can't see whether Dewar shipping is being booked to ensure limits to investigator T&S is applied.

**Comment by stufisher** [comment]
Moved this to jira
