### ISSUE TITLE
Eurpoe/London timezone is hardcoded

### ISSUE THREAD

**Issue by dsclassen** [DiamondLightSource/SynchWeb#96]
There are at least  4 occurrences of `Europe/London` hardcoded into the app.
```
api/index.php:date_default_timezone_set('Europe/London');
api/formulatrix/index.php:date_default_timezone_set('Europe/London');
api/src/Page.php:                    $inputTZ = new \DateTimeZone('Europe/London');
client/src/js/modules/stats/views/breakdown.js:                        timezone: 'Europe/London',
client/src/js/modules/stats/views/breakdown.js:                        timezone: 'Europe/London',
```
It might be good to somehow extract these out to a config file.

**Comment by drnasmith** [comment]
Yes - agreed. We will add a locale configuration parameter in config.php

**Comment by stufisher** [comment]
Theres still a bit of work to do to make this completely diamond free. Im working on it :)

**Comment by JunAishima** [comment]
can you also add in "Time at Diamond is:" in the proposal page to use the site_name? It seems like this should be the one using site_name and site_link instead of the copyright notice at the bottom.

**Comment by stufisher** [comment]
Yep can do

**Comment by stufisher** [comment]
https://github.com/DiamondLightSource/SynchWeb/pull/117
